### ISSUE TITLE
Bad spp value in the hip_bags_ref table.

### ISSUE THREAD

**Issue by thoufer** [USFWS/migbirdHIP#6]
In the strataCheck function I was getting a number of rows for states that was telling me that the coot_snipe & rail_gallinule values were "bad" and that the normal strata was NA.  To make this, I'm guessing that you join it on the hip_bags_ref object.. When I query the hip_bags_ref table the spp values is coots_snipe_bag, and rails_gallinules_bag, when the column names in the data are coots_snipe and rails_gallinules which is causing a join issue?

This appears to be isolated to the strataCheck function.  The output files have the correct stratification for these columns, and states.

**Comment by lawalter** [comment]
Corrected with https://github.com/USFWS/migbirdHIP/commit/1cb47052d3ef95b8d875d6540f40e1ccfbfc5beb
