### ISSUE TITLE
record_type assignment for BT permit files 

### ISSUE THREAD

**Issue by thoufer** [USFWS/migbirdHIP#7]
This at the moment appears to be specific to the CO and NM Band-tailed pigeon permit files..  These are uniquely different in that in addition to the permit file, there should be a dove response attached to it.  This differs from the Crane files which are just a positive indicator that a crane permit was purchased.

In 2024, a record_type of PMT was attached for each of these records, when creating the output transfer file.  These should have been tagged as HIP since they include "non-permit information".  The impact appears that a hip registration was not created to capture the dove stratification.  However, this may have been limited to those records in which the state could not match the permit to a hunter with a HIP registration, which means we would have been creating a HIP registration with a dove stratum of 0..

**Options:**
A. update code to just make sure these are assigned to HIP 
B. Discuss whether we can do away with the record_type column altogether since I can identify what columns in what states are permit fields, and just process accordingly.

**Comment by lawalter** [comment]
All BTPI permit file records will be classified as `record_type = "HIP"` in permit pre-processing.
